### ISSUE TITLE
TypeError: Cannot read property 'canvasId' of undefined

### ISSUE THREAD

**Issue by mbabatunde** [alexandermendes/vue-confetti#32]
Hi,

I'm currently experiencing an issue with use your custom component.

Currently, I'm using the example you provided in your README. For some reason,  I'm constantly facing this issue when testing on Google Chrome:

```
vue.esm.js?efeb:628 
[Vue warn]: Error in v-on handler: 
"TypeError: Cannot read property 'canvasId' of undefined"
```

Currently, my code looks like this in one of my components:
```vue
<template>
<main>
    <div class="home">
        <img src="../assets/avataaars.svg">
        <h1>Hello, I'm {{ name }}!</h1>
        <h3>Student. Developer. Artist.</h3>
        <button @click='start'>Throw Confetti!</button>
        <button @click='stop'>No More Confetti</button>
    </div>
  </main>
</template>

<script>
import Vue from 'vue';
import VueConfetti from 'vue-confetti';

Vue.use(VueConfetti);

export default {
  name: 'Home',
  data() {
    return {
      name: 'Mark Babatunde',
    };
  },
  methods: {
    start() {
      this.$confetti.start();
    },
    stop() {
      this.$confetti.stop();
    },
  },
};
</script>
```

If you have suggestions on figuring out this issue, I would greatly appreciate it.

**Comment by alexandermendes** [comment]
Hi, could you share the stack trace so I can see where the error is being thrown from? Also, what version of vue-confetti are you running?

**Comment by alexandermendes** [comment]
Ah, I suspect it might work with `this.$confetti.start({});`, but this should be fixed, thanks for pointing it out.

**Comment by mbabatunde** [comment]
Hi, I'm still facing the same issue with `this.$confetti.start({})`.

I'm currently using `"vue-confetti": "^2.0.1"`

Stack Trace from Chrome 76:
```javascript
[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'start' of undefined"

found in

---> <Home> at src/components/Home.vue
       <App> at src/App.vue
         <Root>
```

Stack Trace from Firefox 68:
```javascript
[Vue warn]: Error in v-on handler: "TypeError: this.$confetti is undefined"

found in

---> <Home> at src/components/Home.vue
       <App> at src/App.vue
         <Root>
```

**Home.vue** Component:
```vue
<template>
  <div class="home">
      <img src="../assets/avataaars.svg">
      <h1>Hello, I'm {{ name }}!</h1>
      <h3>Student. Developer. Artist.</h3>
      <button @click='start'>Throw Confetti!</button>
      <button @click='stop'>No More Confetti</button>
  </div>
</template>

<script>
import Vue from 'vue';
import VueConfetti from 'vue-confetti';

export default {
  name: 'Home',
  data() {
    return {
      name: 'Mark Babatunde',
    };
  },
  methods: {
    start() {
      this.$confetti.start({});
    },
    stop() {
      this.$confetti.stop({});
    },
  },
};
</script>
```

**Comment by im-amendes** [comment]
So `this.$confetti` is undefined, why might that be?

**Comment by alexandermendes** [comment]
So `this.$confetti` is undefined, why might that be?

**Comment by alexandermendes** [comment]
From your snippet it looks like the plugin isn't being registered? See https://nuxtjs.org/guide/plugins/#vue-plugins

**Comment by alexandermendes** [comment]
Nope

**Comment by alexandermendes** [comment]
Check the errors in the snippets you posted again. They say this.$confetti is undefined, because the plugin isn't registered.

**Comment by alexandermendes** [comment]
Have just pushed up a fix for the original `confetti.start` issue. Closing this as the subsequent issue seemed to be something else. Feel free to reopen if it's still an issue.
